<?php

/**
 * @file
 * Implements hooks for the y_pef_schedule module.
 */

declare(strict_types = 1);

/**
 * Implements hook_preprocess_page().
 */
function y_pef_schedule_preprocess_page(&$variables): void {
  $variables['#attached']['library'][] = 'y_pef_schedule/y_pef_schedule-app';
}

/**
 * Implements hook_theme().
 */
function y_pef_schedule_theme(): array {
  return [
    'branches_list' => [
      'variables' => [
        'branches' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_library_info_alter().
 */
function y_pef_schedule_library_info_alter(&$libraries, $extension): void {
  if (\Drupal::routeMatch()->getRouteName() === 'y_pef_schedule.fullcalendar' && $extension === 'claro') {
    unset($libraries['global-styling']['css']['component']['css/components/tables.css']);
  }
}
